root: true
parser: "@typescript-eslint/parser"
extends:
    - "plugin:adonis/typescriptApp"
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:unicorn/recommended"
    - "prettier"
plugins:
    - "@typescript-eslint"
rules:
    unicorn/filename-case: 0
    unicorn/prevent-abbreviations: 0
    unicorn/no-null: 0
    unicorn/text-encoding-identifier-case: 0
    "@typescript-eslint/no-empty-interface": 0
ignorePatterns:
    - "node_modules"
    - "build"
    - "resources/js"
